### PR TITLE
Add support for Intermec Wedge Spy driver.

### PR DESCRIPTION
**Pull request by kenfletcher**

### CODE REVIEW

**Comment by kenfletcher** [comment]
I did test it on a motion tablet!

**Comment by johnposten** [comment]
@psurey Can you confirm that this is working or not working on the WAPA tablet?  We will need it working by next week I believe.

**Comment by kenfletcher** [comment]
I hope this is resolved and put to bed
the main source of confusion had to do with the name of the driver
Initially I called it WedgeLite because that was the name of the wedge on
the motion tablet

and then we found another program on another tablet that behaves in exactly
the same way with the same Intermec SDK API etc.

and so it was renamed to Intermec Wedge Spy as that is the basic thing we
hook into (Intermec SDK specfic)

**Comment by psurey** [comment]
It is no longer working on any of the motion tablets.

**Comment by johnposten** [comment]
@kenfletcher can you work with Peter to make sure that he was doing everything correctly, since it was supposedly working?

**Comment by kenfletcher** [comment]
sure, will try
these motion tablets seem to be kicking our (something or other)

**Comment by johnposten** [comment]
What was the result of this?  Peter could you provide more details about what you tried and what is not working.  Next week is the 3rd week since the change in the WAPA project and we said it would be working by then.

**Comment by psurey** [comment]
Upon further investigation, it appears that an older version of uniwedge was still present on the WAPA tablet.  I removed it and now am able to detect the intermec wedge spy.  However, it seems to be working more as a keyboard wedge.  I can scan into a field, but that is all.  It will not apply any actions to the scan.

**Comment by johnposten** [comment]
Well that is encouraging.  Are you sure that you were testing on a view that has barcode scan events defined?

**Pull request merged**
